# Generated by Django 4.0.2 on 2022-02-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('picture', models.ImageField(upload_to='cool_coding_images')),
            ],
            options={
                'verbose_name_plural': 'Coding Pics',
            },
        ),
        migrations.CreateModel(
            name='DogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('dog_age', models.IntegerField()),
                ('dog_owner', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Dog Info',
            },
        ),
    ]
